#!/bin/ansible-playbook
#
# Title:      SabNZBD Subtask
# Author(s):  MrDoob
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Set Known Facts'
      set_fact:
        app: 'sabnzbd'
        path: '/mnt'
    - name: 'Register Domain'
      shell: cat /etc/hosts | grep 127.0.0.1 | tail -n 1 | awk '{print $2}'
      register: domain
    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/{{app}}/sabnzbd.ini
      register: inicheck
    - name: 'Waiting for {{app}} to initialize'
      wait_for:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        state: present
        delay: 5
    - name: 'Stopping {{app}}'
      shell: 'docker stop {{app}}'
    - name: 'Set download_dir when incomplete is undefined'
      ini_file:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        section: misc
        option: download_dir
        value: '{{path}}/incomplete/nzb'
        state: present
    - name: 'Set complete_dir'
      ini_file:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        section: misc
        option: complete_dir
        value: '{{path}}/downloads/nzb'
        state: present
    - name: 'Set nzb watch location'
      ini_file:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        section: misc
        option: dirscan_dir
        value: '{{path}}/nzb/watch'
        state: present
    - name: 'Set nzb backup location'
      ini_file:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        section: misc
        option: nzb_backup_dir
        value: '{{path}}/nzb'
        state: present
    - name: 'set script_dir'
      ini_file:
        path: '/opt/appdata/{{app}}/sabnzbd.ini'
        section: misc
        option: script_dir
        value: scripts
        state: present
    - name: 'Configuring {{app}} for first time use'
      block:
        - name: 'Set host_whitelist'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: host_whitelist
            value: 'sabnzbd.{{domain}},sabnzbd'
            state: present
        - name: 'Set direct_unpack'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: direct_unpack
            value: '1'
            state: present
        - name: 'Set ignore_samples'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: ignore_samples
            value: '1'
            state: present
        - name: 'Set max logging lines'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: max_log_size
            value: '524'
            state: present
        - name: 'Set max logging days'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: log_backups
            value: '1'
            state: present
        - name: 'set unwanted_extensions'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: unwanted_extensions
            value: exe, com, bat, sh, iso, m2ts, mt2s
            state: present
        - name: 'set cleanup_list'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: cleanup_list
            value: nfo, exe, com, bat, txt, doc, xls, xlxs, docx, doc, jpg, jeg, gif, png
            state: present
        - name: 'set Cache Limit to 4G'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: cache_limit
            value: 4G
            state: present
        - name: 'set action_on_unwanted_extensions'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: action_on_unwanted_extensions
            value: '2'
            state: present
        - name: 'set pause_on_pwrar - aborts encrypted rar rather than pausing'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: pause_on_pwrar
            value: '2'
            state: present
        - name: 'set new_nzb_on_failure - try a new nzb if it fails'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: new_nzb_on_failure
            value: '1'
            state: present
        - name: 'set flat_unpack'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: flat_unpack
            value: '1'
            state: present
        - name: 'set download_free'
          ini_file:
            path: '/opt/appdata/{{app}}/sabnzbd.ini'
            section: misc
            option: download_free
            value: '25G'
            state: present
      when: inicheck.stat.exists
